version: "3.9"

# Optional example override: publish individual dev server ports only on loopback
# Use with: docker compose -f docker-compose.yml -f docker-compose.local-only-example.yml up

services:
  welcome-frontend:
    ports:
      - "127.0.0.1:9000:9000"
  farmer-frontend:
    ports:
      - "127.0.0.1:9100:9000"  # host 9100 -> container 9000
  regulator-frontend:
    ports:
      - "127.0.0.1:9101:9001"
  auditor-frontend:
    ports:
      - "127.0.0.1:9102:9001"
  retail-frontend:
    ports:
      - "127.0.0.1:9103:9001"
  laboratory-frontend:
    ports:
      - "127.0.0.1:9104:9001"

# Reverse proxy already bound to 127.0.0.1:9000 in base file.