# Volumes for persistent data and node_modules
volumes:
  postgres-data:
  auditor_node_modules:
  regulator_node_modules:
version: '3.9'  # Note: version field is deprecated but kept for compatibility
services:
  auditor-frontend:
    build:
      context: ./auditor-frontend
    environment:
      VITE_USE_API_PROXY: 'true'
      VITE_API_URL: http://backend:3001
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
      NODE_ENV: development
      DEBUG: 'vite:*'
    ports:
      - "4000:4000"
  # backend removed; no dependency
    volumes:
      - ./auditor-frontend:/app
      - auditor_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"

  regulator-frontend:
    build:
      context: ./regulator-frontend
    environment:
      VITE_USE_API_PROXY: 'true'
      VITE_API_URL: http://backend:3001
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
      NODE_ENV: development
      DEBUG: 'vite:*'
      VITE_HMR_PORT: '24679'
    ports:
      - "2000:5000"
      - "24679:24679"
  # backend removed; no dependency
    volumes:
      - ./regulator-frontend:/app
      - regulator_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: trace_user
      POSTGRES_PASSWORD: trace_password
      POSTGRES_DB: traceability
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # backend service removed

