# Volumes for persistent data and node_modules
volumes:
  auditor_node_modules:
  regulator_node_modules:
  shop_node_modules:
  laboratory_node_modules:
version: '3.9'  # Note: version field is deprecated but kept for compatibility
services:
  auditor-frontend:
    build:
      context: ./auditor-frontend
    environment:
      VITE_USE_API_PROXY: 'true'
      VITE_API_URL: http://backend:3001
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
      NODE_ENV: development
      DEBUG: 'vite:*'
    ports:
      - "4000:4000"
  # backend removed; no dependency
    volumes:
      - ./auditor-frontend:/app
      - auditor_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"

  regulator-frontend:
    build:
      context: ./regulator-frontend
    environment:
      VITE_USE_API_PROXY: 'true'
      VITE_API_URL: http://backend:3001
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
      NODE_ENV: development
      DEBUG: 'vite:*'
      VITE_HMR_PORT: '24679'
    ports:
      - "2000:5000"
      - "24679:24679"
  # backend removed; no dependency
    volumes:
      - ./regulator-frontend:/app
      - regulator_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"

  shop-frontend:
    build:
      context: ./shop-frontend
    environment:
      VITE_USE_API_PROXY: 'true'
      VITE_API_URL: http://backend:3001
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
      NODE_ENV: development
      DEBUG: 'vite:*'
      VITE_HMR_PORT: '24680'
    ports:
      - "9000:9000"
      - "24680:24680"
    volumes:
      - ./shop-frontend:/app
      - shop_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"

  laboratory-frontend:
    build:
      context: ./laboratory-frontend
    environment:
      VITE_USE_API_PROXY: 'true'
      VITE_API_URL: http://backend:3001
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
      NODE_ENV: development
      DEBUG: 'vite:*'
      VITE_HMR_PORT: '24681'
    ports:
      - "9100:9000"
      - "24681:24681"
    volumes:
      - ./laboratory-frontend:/app
      - laboratory_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"
  # db service removed

  # backend service removed

