version: '3.9'
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: trace_user
      POSTGRES_PASSWORD: trace_password
      POSTGRES_DB: traceability
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    # Map backend to host 3002 to avoid conflicts with local dev on 3001
    ports:
      - "3002:3001"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev

  frontend:
    build:
      context: ./frontend
    environment:
      # The browser runs on the host, so point to host-mapped backend port
      VITE_API_URL: http://localhost:3002
      # Google Maps API key for Vite (read from top-level .env)
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
    ports:
      - "5173:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

volumes:
  postgres-data:
