version: "3.9"

services:
  # Keycloak (admin) - bind to localhost only so it's accessible only via host nginx reverse-proxy
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command: ["start-dev"]
    env_file: .env
    environment:
      # KEYCLOAK_ADMIN and KEYCLOAK_ADMIN_PASSWORD come from .env
      PROXY_ADDRESS_FORWARDING: "true"
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - "127.0.0.1:8080:8080"   # bound to localhost only
    networks:
      - mvp_net

  # oauth2-proxy: bind to localhost so only host nginx can reach it (it enforces auth for s2s-mvp)
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:7.4.0
    env_file: .env
    environment:
      OAUTH2_PROXY_PROVIDER: oidc
      # Public issuer (use the auth subdomain that nginx will proxy to Keycloak)
      OAUTH2_PROXY_OIDC_ISSUER_URL: ${OAUTH2_PROXY_OIDC_ISSUER_URL}
      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_UPSTREAMS: http://session-proxy:7000/
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_REDIRECT_URL: ${OAUTH2_PROXY_REDIRECT_URL}
      OAUTH2_PROXY_COOKIE_SECURE: "true"
      OAUTH2_PROXY_COOKIE_SAMESITE: "Lax"
    ports:
      - "127.0.0.1:4180:4180"  # bound to localhost only; host nginx will proxy to this
    depends_on:
      - keycloak
      - session-proxy
    networks:
      - mvp_net

  # Session-proxy: internal only, sits behind oauth2-proxy and proxies to welcome frontend
  session-proxy:
    image: session-proxy:latest
    build:
      context: ./session-proxy
    environment:
      PORT: 7000
    depends_on:
      - welcome-frontend
    networks:
      - mvp_net

  # All frontends should NOT be published to the host in production - they remain internal to Docker network
  welcome-frontend:
    build:
      context: ./welcome-frontend
    environment:
      VITE_USE_API_PROXY: "false"
      NODE_ENV: production
    volumes:
      - welcome_node_modules:/app/node_modules
    command: sh -c "npm ci && npm run build && npm run preview -- --port 9000 --host 0.0.0.0"
    networks:
      - mvp_net

  auditor-frontend:
    build:
      context: ./auditor-frontend
    networks:
      - mvp_net

  regulator-frontend:
    build:
      context: ./regulator-frontend
    networks:
      - mvp_net

  retail-frontend:
    build:
      context: ./retail-frontend
    networks:
      - mvp_net

  farmer-frontend:
    build:
      context: ./farmer-frontend
    networks:
      - mvp_net

  laboratory-frontend:
    build:
      context: ./laboratory-frontend
    networks:
      - mvp_net

volumes:
  keycloak_data:
  welcome_node_modules:

networks:
  mvp_net:
    driver: bridge
