version: "3.9"

volumes:
  auditor_node_modules:
  regulator_node_modules:
  retail_node_modules:
  laboratory_node_modules:
  welcome_node_modules:
  farmer_node_modules:

services:
  auditor-frontend:
    build:
      context: ./auditor-frontend
    environment:
      VITE_USE_API_PROXY: "true"
      VITE_API_URL: http://backend:3001
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
      NODE_ENV: development
      DEBUG: "vite:*"
      VITE_HMR_PORT: "24680"
    ports:
      - "9002:9001"
      - "24680:24680"
    volumes:
      - ./auditor-frontend:/app
      - auditor_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"

  regulator-frontend:
    build:
      context: ./regulator-frontend
    environment:
      VITE_USE_API_PROXY: "true"
      VITE_API_URL: http://backend:3001
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
      NODE_ENV: development
      DEBUG: "vite:*"
      VITE_HMR_PORT: "24679"
    ports:
      - "9001:9001"
      - "24679:24679"
    volumes:
      - ./regulator-frontend:/app
      - regulator_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"

  retail-frontend:
    build:
      context: ./retail-frontend
    environment:
      VITE_USE_API_PROXY: "true"
      VITE_API_URL: http://backend:3001
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
      NODE_ENV: development
      DEBUG: "vite:*"
      VITE_HMR_PORT: "24683"
    ports:
      - "9004:9001"
      - "24683:24683"
    volumes:
      - ./retail-frontend:/app
      - retail_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"

  farmer-frontend:
    build:
      context: ./farmer-frontend
    environment:
      VITE_USE_API_PROXY: "true"
      VITE_API_URL: http://backend:3001
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
      NODE_ENV: development
      DEBUG: "vite:*"
      VITE_HMR_PORT: "24682"
    ports:
      - "9003:9000"
      - "24682:24682"
    volumes:
      - ./farmer-frontend:/app
      - farmer_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev -- --port 9000"

  laboratory-frontend:
    build:
      context: ./laboratory-frontend
    environment:
      VITE_USE_API_PROXY: "true"
      VITE_API_URL: http://backend:3001
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
      NODE_ENV: development
      DEBUG: "vite:*"
      VITE_HMR_PORT: "24681"
    ports:
      - "9005:9001"
      - "24681:24681"
    volumes:
      - ./laboratory-frontend:/app
      - laboratory_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"

  welcome-frontend:
    build:
      context: ./welcome-frontend
    environment:
      VITE_USE_API_PROXY: "false"
      NODE_ENV: development
      DEBUG: "vite:*"
      VITE_HMR_PORT: "24678"
    ports:
      - "9000:9000"
      - "24678:24678"
    volumes:
      - ./welcome-frontend:/app
      - welcome_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"

