version: "3.9"

volumes:
  auditor_node_modules:
  regulator_node_modules:
  retail_node_modules:
  laboratory_node_modules:
  welcome_node_modules:
  farmer_node_modules:

services:
  # -------------------------------------------------------------
  # PUBLIC ENTRY (local dev): reverse-proxy (nginx)
  # For local development we add an nginx container that:
  #  - Authenticates all requests (except /oauth2/*) via oauth2-proxy
  #  - Routes path prefixes to each internal frontend
  #  - Serves welcome app at '/'
  # In production you will replicate this logic in your host nginx
  # (so your existing website vhost stays untouched) rather than
  # necessarily running this container. The container is provided
  # to validate the zero-trust / path-based multi‑app layout locally.
  reverse-proxy:
    image: nginx:1.27-alpine
    depends_on:
      - oauth2-proxy
      - welcome-frontend
      - regulator-frontend
      - auditor-frontend
      - farmer-frontend
      - retail-frontend
      - laboratory-frontend
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    # This is the single public port for the MVP user entry (was welcome :9000)
    ports:
      - "9000:80"
    networks:
      - mvp_public
      - mvp_internal

  auditor-frontend:
    build:
      context: ./auditor-frontend
    environment:
      VITE_USE_API_PROXY: "true"
      VITE_API_URL: http://backend:3001
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
      NODE_ENV: development
      DEBUG: "vite:*"
      VITE_HMR_PORT: "24680"
    # Do not publish frontend ports to the host. Keep them internal-only so
    # they are only reachable from other containers (eg. oauth2-proxy).
    expose:
      - "9001"
      - "24680"
    volumes:
      - ./auditor-frontend:/app
      - auditor_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"

  regulator-frontend:
    build:
      context: ./regulator-frontend
    environment:
      VITE_USE_API_PROXY: "true"
      VITE_API_URL: http://backend:3001
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
      NODE_ENV: development
      DEBUG: "vite:*"
      VITE_HMR_PORT: "24679"
    expose:
      - "9001"
      - "24679"
    volumes:
      - ./regulator-frontend:/app
      - regulator_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"

  retail-frontend:
    build:
      context: ./retail-frontend
    environment:
      VITE_USE_API_PROXY: "true"
      VITE_API_URL: http://backend:3001
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
      NODE_ENV: development
      DEBUG: "vite:*"
      VITE_HMR_PORT: "24683"
    expose:
      - "9001"
      - "24683"
    volumes:
      - ./retail-frontend:/app
      - retail_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"

  farmer-frontend:
    build:
      context: ./farmer-frontend
    environment:
      VITE_USE_API_PROXY: "true"
      VITE_API_URL: http://backend:3001
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
      NODE_ENV: development
      DEBUG: "vite:*"
      VITE_HMR_PORT: "24682"
    expose:
      - "9000"
      - "24682"
    volumes:
      - ./farmer-frontend:/app
      - farmer_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev -- --port 9000"

  laboratory-frontend:
    build:
      context: ./laboratory-frontend
    environment:
      VITE_USE_API_PROXY: "true"
      VITE_API_URL: http://backend:3001
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
      NODE_ENV: development
      DEBUG: "vite:*"
      VITE_HMR_PORT: "24681"
    expose:
      - "9001"
      - "24681"
    volumes:
      - ./laboratory-frontend:/app
      - laboratory_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"

  welcome-frontend:
    build:
      context: ./welcome-frontend
    environment:
      VITE_USE_API_PROXY: "false"
      NODE_ENV: development
      DEBUG: "vite:*"
      VITE_HMR_PORT: "24678"
    expose:
      - "9000"
      - "24678"
    volumes:
      - ./welcome-frontend:/app
      - welcome_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"

  # Keycloak identity provider (development mode). Admin user is created from
  # environment variables. Keycloak listens on 8080 internally. We keep it on
  # the internal network only by default; for local testing we map the port to
  # the host. On the VPS we'll expose it only on the auth subdomain via nginx.
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    networks:
      - mvp_internal

  # oauth2-proxy performs authentication via Keycloak and proxies requests to
  # the internal frontends. This is the only service we'll expose publicly
  # for the MVP (it will be bound to your s2s-mvp domain on the VPS). For
  # local testing we map to host port 9006, but on the VPS you should route
  # your public domain to this container (or an nginx reverse proxy that
  # forwards to it).
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    restart: unless-stopped
    # Only oauth2-proxy (and keycloak admin) need host exposure locally.
    # reverse-proxy talks to oauth2-proxy internally on 4180.
    ports:
      - "9006:4180"
    env_file:
      - ./.env
    environment:
      OAUTH2_PROXY_PROVIDER: "oidc"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "http://keycloak:8080/realms/mvp"
      OAUTH2_PROXY_CLIENT_ID: "mvp-client"
      OAUTH2_PROXY_CLIENT_SECRET: "${OAUTH2_PROXY_CLIENT_SECRET}"
      OAUTH2_PROXY_COOKIE_SECRET: "${COOKIE_SECRET}"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_REDIRECT_URL: "http://127.0.0.1:9006/oauth2/callback"
      # Upstreams list is unused with auth_request pattern but required.
      # We keep welcome so direct access still works for testing.
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_UPSTREAMS: "http://welcome-frontend:9000/"
      # Allow nginx auth_request probe without redirect loop
      OAUTH2_PROXY_SKIP_AUTH_ROUTES: "/oauth2/healthz"
    depends_on:
      - keycloak
      - welcome-frontend
    networks:
      - mvp_internal
      - mvp_public

networks:
  mvp_internal:
    driver: bridge
  mvp_public:
    driver: bridge

